# Complete Example: Managing Cachix Binary Caches with Terraform
#
# This example demonstrates a complete setup including:
# - Provider configuration with variables
# - Creating multiple caches for different environments
# - Referencing existing public caches
# - Generating nix.conf configuration
# - Outputting values for CI/CD integration

terraform {
  required_version = ">= 1.0"

  required_providers {
    cachix = {
      source  = "takeokunn/cachix"
      version = "~> 0.1"
    }
  }
}

# -----------------------------------------------------------------------------
# Variables
# -----------------------------------------------------------------------------

variable "cachix_token" {
  description = "Cachix API authentication token"
  type        = string
  sensitive   = true
  default     = null # Falls back to CACHIX_AUTH_TOKEN env var
}

variable "project_name" {
  description = "Base name for the project caches"
  type        = string
  default     = "my-project"
}

variable "environments" {
  description = "List of environments to create caches for"
  type        = list(string)
  default     = ["dev", "staging", "prod"]
}

# -----------------------------------------------------------------------------
# Provider Configuration
# -----------------------------------------------------------------------------

provider "cachix" {
  auth_token = var.cachix_token
}

# -----------------------------------------------------------------------------
# Data Sources: Reference Existing Caches
# -----------------------------------------------------------------------------

# Get current authenticated user information
data "cachix_user" "current" {}

# Reference well-known public caches
data "cachix_cache" "nix_community" {
  name = "nix-community"
}

data "cachix_cache" "devenv" {
  name = "devenv"
}

# -----------------------------------------------------------------------------
# Resources: Create Project Caches
# -----------------------------------------------------------------------------

# Main project cache (public)
resource "cachix_cache" "main" {
  name      = var.project_name
  is_public = true
}

# Environment-specific caches (private)
resource "cachix_cache" "env" {
  for_each = toset(var.environments)

  name      = "${var.project_name}-${each.key}"
  is_public = each.key == "prod" ? false : true
}

# -----------------------------------------------------------------------------
# Outputs: Values for Integration
# -----------------------------------------------------------------------------

# Current user information
output "authenticated_user" {
  description = "The authenticated Cachix user"
  value       = data.cachix_user.current.username
}

# Main cache information
output "main_cache" {
  description = "Main project cache details"
  value = {
    name              = cachix_cache.main.name
    uri               = cachix_cache.main.uri
    is_public         = cachix_cache.main.is_public
    public_signing_keys = cachix_cache.main.public_signing_keys
  }
}

# Environment caches
output "environment_caches" {
  description = "Environment-specific cache URIs"
  value = {
    for env, cache in cachix_cache.env : env => {
      uri       = cache.uri
      is_public = cache.is_public
    }
  }
}

# Generate nix.conf substituters configuration
output "nix_substituters" {
  description = "Substituters line for nix.conf"
  value = join(" ", concat(
    [cachix_cache.main.uri],
    [for cache in cachix_cache.env : cache.uri],
    [data.cachix_cache.nix_community.uri],
    [data.cachix_cache.devenv.uri]
  ))
}

# Generate nix.conf trusted-public-keys configuration
output "nix_trusted_public_keys" {
  description = "Trusted public keys for nix.conf"
  value = join(" ", concat(
    cachix_cache.main.public_signing_keys,
    flatten([for cache in cachix_cache.env : cache.public_signing_keys]),
    data.cachix_cache.nix_community.public_signing_keys,
    data.cachix_cache.devenv.public_signing_keys
  ))
}

# Complete nix.conf extra configuration
output "nix_extra_config" {
  description = "Complete extra configuration for nix.conf"
  value = <<-EOT
    # Generated by Terraform - Cachix Provider
    # User: ${data.cachix_user.current.username}

    extra-substituters = ${join(" ", concat(
      [cachix_cache.main.uri],
      [for cache in cachix_cache.env : cache.uri],
      [data.cachix_cache.nix_community.uri],
      [data.cachix_cache.devenv.uri]
    ))}

    extra-trusted-public-keys = ${join(" ", concat(
      cachix_cache.main.public_signing_keys,
      flatten([for cache in cachix_cache.env : cache.public_signing_keys]),
      data.cachix_cache.nix_community.public_signing_keys,
      data.cachix_cache.devenv.public_signing_keys
    ))}
  EOT
}

# GitHub Actions environment variables
output "github_actions_env" {
  description = "Environment variables for GitHub Actions"
  value = {
    CACHIX_CACHE_NAME = cachix_cache.main.name
    CACHIX_CACHE_URI  = cachix_cache.main.uri
  }
}
